slice_name: Deck.gl Path
description: null
certified_by: null
certification_details: null
viz_type: deck_path
params:
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  datasource: 12__table
  js_columns:
  - color
  js_data_mutator: "data => data.map(d => ({\n    ...d,\n    color: colors.hexToRGB(d.extraProps.color)\n\
    }));"
  js_onclick_href: ''
  js_tooltip: ''
  line_column: path_json
  line_type: json
  line_width: 150
  mapbox_style: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  reverse_long_lat: false
  row_limit: 5000
  slice_id: 43
  time_grain_sqla: null
  time_range: ' : '
  viewport:
    altitude: 1.5
    bearing: 0
    height: 1094
    latitude: 37.73671752604488
    longitude: -122.18885402582598
    maxLatitude: 85.05113
    maxPitch: 60
    maxZoom: 20
    minLatitude: -85.05113
    minPitch: 0
    minZoom: 0
    pitch: 0
    width: 669
    zoom: 9.51847667620428
  viz_type: deck_path
query_context: null
cache_timeout: null
uuid: 6332daf6-e442-469d-b66c-a6a38423d4c7
version: 1.0.0
dataset_uuid: 151c283f-c076-437a-8e2f-1cf65fe6db0d
