slice_name: Number of California Births
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: big_number_total
query_context: null
cache_timeout: null
uuid: 400ee69f-eda4-5fe8-bc30-299184e08048
version: 1.0.0
dataset_uuid: 4ec507ac-bece-4d2b-8dc3-cfb7c3515e76
