slice_name: Top 10 California Names Timeseries
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '10'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  time_range: '100 years ago : now'
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  viz_type: echarts_timeseries_line
query_context: null
cache_timeout: null
uuid: 6a587b9e-e28b-5c2a-abb9-c6c1f4fd56b5
version: 1.0.0
dataset_uuid: 4ec507ac-bece-4d2b-8dc3-cfb7c3515e76
