table_name: bart_lines
main_dttm_col: null
description: BART lines
default_endpoint: null
offset: 0
cache_timeout: null
catalog: null
schema: public
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
folders: null
uuid: 151c283f-c076-437a-8e2f-1cf65fe6db0d
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(255)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: color
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(255)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: path_json
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: polyline
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://cdn.jsdelivr.net/gh/apache-superset/examples-data@master/bart-lines.json.gz
