table_name: birth_names
main_dttm_col: ds
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: null
schema: public
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
folders: null
uuid: 4ec507ac-bece-4d2b-8dc3-cfb7c3515e76
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
- metric_name: sum__num
  verbose_name: null
  metric_type: null
  expression: SUM(num)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: num_california
  verbose_name: null
  is_dttm: false
  is_active: true
  type: null
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
  description: null
  python_date_format: null
  extra: null
- column_name: ds
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: state
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(10)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: gender
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(16)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(255)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: num_boys
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: num_girls
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: num
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://cdn.jsdelivr.net/gh/apache-superset/examples-data@master/birth_names2.json.gz
