table_name: flights
main_dttm_col: ds
description: Random set of flights in the US
default_endpoint: null
offset: 0
cache_timeout: null
catalog: null
schema: public
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
folders: null
uuid: 92980b06-cbec-4f34-9c2e-7308edc8c2b9
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: ds
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITHOUT TIME ZONE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: LATE_AIRCRAFT_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: ARRIVAL_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DEPARTURE_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: WEATHER_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIRLINE_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIR_SYSTEM_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: ARRIVAL_TIME
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: SECURITY_DELAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: LATITUDE_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: ELAPSED_TIME
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DEPARTURE_TIME
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: LATITUDE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIR_TIME
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: TAXI_IN
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: TAXI_OUT
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: LONGITUDE_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: LONGITUDE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: WHEELS_OFF
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: WHEELS_ON
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: CANCELLATION_REASON
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: SCHEDULED_ARRIVAL
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DESTINATION_AIRPORT
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: CANCELLED
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: SCHEDULED_DEPARTURE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DISTANCE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DAY_OF_WEEK
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DAY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: TAIL_NUMBER
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: YEAR
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: STATE_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIRPORT_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIRLINE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: STATE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: ORIGIN_AIRPORT
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AIRPORT
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: FLIGHT_NUMBER
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: SCHEDULED_TIME
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: DIVERTED
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MONTH
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: CITY_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: COUNTRY_DEST
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: CITY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: COUNTRY
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: a2dc77af-e654-49bb-b321-40f6b559a1ee
data: https://cdn.jsdelivr.net/gh/apache-superset/examples-data@master/flight_data.csv.gz
