slice_name: Treemap
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  - country_code
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: treemap_v2
query_context: null
cache_timeout: null
uuid: fc941a12-88a0-42e7-ac48-c1ec4ed84640
version: 1.0.0
dataset_uuid: 3b851597-e0e9-42a1-83e4-55547811742e
