slice_name: World's Pop Growth
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: echarts_area
query_context: null
cache_timeout: null
uuid: e18b5d28-3a3d-43ea-8a20-b198b44b08e3
version: 1.0.0
dataset_uuid: 3b851597-e0e9-42a1-83e4-55547811742e
